source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'AirShareTests' do
  pod "AirShare/UIKit", :path => "../"
end

target 'AirShareDemo' do
  pod 'PureLayout'
  pod "AirShare/UIKit", :path => "../"
end

